data_arguments:
  seed: 1314
  param_dir: "../experiments/outputs/lstm_Random_1314"
  data_name: "Random"
  model_name: "lstm"

model_arguments:
  num_layers: 3
  hidden_size: 768
  padding_ids: 0
  dropout: 0.1

generate_argunents:
  per_gpu_test_batch_size: 512
  gen_number: 512
  max_length: 100
  no_cuda: false
  local_rank: -1

output_arguments:
  output_dir: "../experiments/outputs"