version: "1.0"

train:
  - name: MoFlowGenerate
    epochs: 1
    max_atoms: 9

predict:
  - name: RNNGenerate
    n_sample: 10000

metric:
  - name: ValidMetic
  - name: UniqueMetic
  - name: NoveltyMetric
