version: "1.0"

train:
  - name: VAEGenerate
    batch_size: 512
    epochs: 1

predict:
  - name: VAEGenerate
    n_sample: 10000

metric:
  - name: ValidMetic
  - name: UniqueMetic
  - name: NoveltyMetric
